### ISSUE TITLE
Precompile rake task is not available

### ISSUE THREAD

**Issue by dgmstuart** [rstacruz/sinatra-assetpack#194]
I'm using version 0.3.3 (the latest?) 

For some reason `rake assetpack:precompile` described in the docs doesn't work, but `rake asset:build does` - even though this seems to have been deleted?

**Comment by doomspork** [comment]
`0.3.3` was shipped on April 29th ([releases](https://github.com/rstacruz/sinatra-assetpack/releases)), the changes you're referencing were made on the 30th ([commit](https://github.com/rstacruz/sinatra-assetpack/commit/690e6cc6cf31bff3cbe2ffa0e2e917a0bd91527d)).

There's been a number of changes since `0.3.3': https://github.com/rstacruz/sinatra-assetpack/compare/v0.3.3...master

**Comment by dgmstuart** [comment]
Ah OK - I guess it's not really as maintained as I thought then, if a new gem hasn't been cut in nearly a year. Doesn't sound like something I should be using in production - I'll look for other options. Thanks for your help :)

**Comment by doomspork** [comment]
@dgmstuart it looks like the project is in need of new maintainers: https://github.com/rstacruz/sinatra-assetpack/issues/197

**Comment by dgmstuart** [comment]
@doomspork ah right. Not me I'm afraid.
